
#ifndef C_BREAKABLE_HPP
#define C_BREAKABLE_HPP

#define NUM_BALLOON_UP 10
#define NUM_RANGE_UP 10
#define NUM_SPEED_UP 7
#define NUM_KICK_UPGRADE 3
#define NUM_RCONTROL_UPGRADE 2
#define NUM_SBALLOON_UPGRADE 2
#define NUM_PIERCE_UPGRADE 2
#define NUM_SPREAD_UPGRADE 1
#define NUM_GHOST_UPGRADE 1
#define NUM_UPGRADE (NUM_BALLOON_UP + NUM_RANGE_UP + NUM_SPEED_UP + NUM_KICK_UPGRADE + NUM_RCONTROL_UPGRADE + NUM_SBALLOON_UPGRADE + NUM_PIERCE_UPGRADE + NUM_SPREAD_UPGRADE + NUM_GHOST_UPGRADE)

#include "../ec/component.hpp"

struct cBreakable : Component
{
    unsigned char health = 1;
};

#endif
