
#ifndef GRID_INFO_HPP
#define GRID_INFO_HPP

#define GRID_WIDTH 15
#define GRID_HEIGHT 15
#define GRID_TOTAL (GRID_WIDTH*GRID_HEIGHT)
#define GRID_SQUARE_SIZE 32
#define GRID_OFFSET_X 120
#define GRID_OFFSET_Y 0
#define GRID_RIGHT (GRID_OFFSET_X + GRID_WIDTH * GRID_SQUARE_SIZE)
#define GRID_BOTTOM (GRID_OFFSET_Y + GRID_HEIGHT * GRID_SQUARE_SIZE)

#endif
